version: 2
sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have one row per product_id found in each orders_id
        # Freshness Testing
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness: 
          warn_after:
            count: 90
            period: day
        columns:
          - name: date_date
            description: satın alma tarihi
          - name: orders_id 
            description: foreign key to ship
          - name: pdt_id
            description: foreign key to product
          - name: revenue
            description: the amount paid by the customer to purchase the product. revenue = quantity * selling_price
          - name: quantity
            description: the quantity of products purchased for a given order
        tests:
          - unique:
              column_name: "(orders_id ||'-'||pdt_id)"
      - name: product
        identifier: raw_gz_product
        description: products of Greenweez
        columns:
          - name: products_id
            description: Primary key
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: the purchase price of the product

      - name: ship
        identifier: raw_gz_ship
        description: shipping data for Greenweez orders
        columns:
          - name: orders_id
            description: Primary key
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: the price the customer pays for shipping
          - name: log_cost
            description: the cost of preparing the parcel in the distribution centre/warehouse
          - name: ship_cost
            description: shipping cost paid by Greenweez to the carrier/logistics provider
      - name: adwords
        identifier: raw_gz_adwords
        description: data for adwords campaigns
      - name: bing
        identifier: raw_gz_bing
        description: data for bing campaigns
      - name: criteo
        identifier: raw_gz_criteo
        description: data for criteo campaigns
      - name: facebook
        identifier: raw_gz_facebook
        description: data for facebook campaigns
models:
  - name: int_campaigns
    description: data from all campaigns
    columns:
    - name: date_date
      description: campaign date
      tests:
        - not_null
    - name: paid_source
      description: shows which campaign it comes from
    - name: campaign_key
      description: id for campaign
      tests:
        - not_null
    - name: campaign_name
      description: name of the campaign
      tests:
        - not_null
    - name: ads_cost
      description: cost of the campaign
    - name: impression
      description: number of impressions of the campaign
    - name: click
      description: number of clicks of the campaign
    tests:
      - unique:
          column_name: "(campaign_key || '-' || date_date)"
  - name: int_campaigns_day
    description: data from campaigns total for day
